// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdhovkaeawupduvaedke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkaG92a2FlYXd1cGR1dmFlZGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzg1NTQsImV4cCI6MjA2NDcxNDU1NH0.X3Es97SagmXaidxKKQ0tQTozc0Zm11LcKZCuXFg_o9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);